apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customer
spec:
  replicas: 1
  template:
    metadata:
      name: customer
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: patikax/customer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: SPRING_DATASOURCE_USERNAME
              value: patika
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://microservice.postgres.database.azure.com:5432/customer
            - name: SPRING_DATASOURCE_PASSWORD
              value: password0-0
      restartPolicy: Always
  selector:
    matchLabels:
      app: customer
