apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
  labels:
    app: fraud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud
  template:
    metadata:
      name: fraud
      labels:
        app: fraud
    spec:
      containers:
        - name: fraud
          image: patikax/fraud:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: SPRING_DATASOURCE_USERNAME
              value: patika
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://microservice.postgres.database.azure.com:5432/fraud
            - name: SPRING_DATASOURCE_PASSWORD
              value: password0-0
      restartPolicy: Always
